services:
  openclaw-gateway:
    build:
      dockerfile: Dockerfile.local
      args:
        OPENCLAW_DOCKER_APT_PACKAGES: "chromium"
    environment:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    volumes:
      - /Users/sergeysmirnov/projects/long-memory:/home/node/.openclaw/workspace/projects/long-memory
      - /Users/sergeysmirnov/projects/openclaw:/home/node/.openclaw/workspace/projects/openclaw
