services:
  openclaw-gateway:
    build:
      dockerfile: Dockerfile.local
      args:
        OPENCLAW_DOCKER_APT_PACKAGES: "chromium"
    environment:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    volumes:
      - /Users/ssmirnov/shprojects:/home/node/.openclaw/workspace/projects
